name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build and analyze
      run: ./mvnw -B clean verify

    - name: Codecov Code Coverage
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests # optional
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: false
